# Generated by Django 2.2.3 on 2019-07-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('regular_price', models.FloatField(null=True)),
                ('sale_price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
            ],
        ),
    ]
