# Generated by Django 2.2.3 on 2019-07-30 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190730_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_divided',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Item_men',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='Item_women',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.Item')),
            ],
            bases=('items.item',),
        ),
    ]
